package org.somecode.enigma

val Wheels: Map[String, String] = Map(
  "IC"      -> "DMTWSILRUYQNKFEJCAZBPGXOHV",
  "IIC"     -> "HQZGPJTMOBLNCIFDYAWVEUSRKX",
  "IIIC"    -> "UQNTLSZFMREHDPXKIBVYGJCWOA",

  "IR"      -> "JGDQOXUSCAMIFRVTPNEWKBLZYH",
  "IIR"     -> "NTZPSFBOKMWRCJDIVLAEYUXHGQ",
  "IIIR"    -> "JVIUBHTCDYAKEQZPOSGXNRMWFL",
  "UKWR"    -> "QYHOGNECVPUZTFDJAXWMKISRBL",
  "ETWR"    -> "QWERTZUIOASDFGHJKPYXCVBNML",

  "IK"      -> "PEZUOHXSCVFMTBGLRINQJWAYDK",
  "IIK"     -> "ZOUESYDKFWPCIQXHMVBLGNJRAT",
  "IIIK"    -> "EHRVXGAOBQUSIMZFLYNWKTPDJC",
  "UKWK"    -> "IMETCGFRAYSQBZXWLHKDVUPOJN",
  "ETWK"    -> "QWERTZUIOASDFGHJKPYXCVBNML",

  "I"       -> "EKMFLGDQVZNTOWYHXUSPAIBRCJ",  
  "II"      -> "AJDKSIRUXBLHWTMCQGZNPYFVOE",  
  "III"     -> "BDFHJLCPRTXVZNYEIWGAKMUSQO",  
  "IV"      -> "ESOVPZJAYQUIRHXLNFTGKDCMWB",
  "V"       -> "VZBRGITYUPSDNHLXAWMJQOFECK",
  "VI"      -> "JPGVOUMFYQBENHZRDKASXLICTW",
  "VII"     -> "NZJHGRCXMYSWBOUFAIVLPEKQDT",
  "VIII"    -> "FKQHTLXOCBJSPDZRAMEWNIUYGV",

  "BETA"    -> "LEYJVCNIXWPBQMDRTAKZGFUHOS",
  "GAMMA"   -> "FSOKANUERHMBTIYCWLQPZXVGJD",
  "REF-A"   -> "EJMZALYXVBWFCRQUONTSPIKHGD",
  "REF-B"   -> "YRUHQSLDPXNGOKMIEBFZCWVJAT",
  "REF-C"   -> "FVPJIAOYEDRZXWGCTKUQSBNMHL",
  "REF-BT"  -> "ENKQAUYWJICOPBLMDXZVFTHRGS",
  "REF-CT"  -> "RDOBJNTKVEHMLFCWZAXGYIPSUQ",
  "ETW"     -> "ABCDEFGHIJKLMNOPQRSTUVWXYZ")
